// ================================================================
// ExcelReportService — professional .xlsx workbook builder (ExcelJS)
// ----------------------------------------------------------------
// Produces a real .xlsx (never CSV). Every sheet is built from the
// SAME aggregated report object used by the preview API, so Excel and
// screen numbers can never diverge.
//
// Features: title blocks, freeze panes, autofilters, real Excel
// tables, styled headers, alternating rows, column widths, wrapped
// text, currency/percent/date number formats, negative-amount display,
// conditional formatting for statuses and top/low products, totals
// rows, landscape print setup with repeated header rows, workbook
// metadata, and formula-injection protection.
//
// Charts / slicers: ExcelJS has no native chart or slicer engine, so
// all charts are rendered in the in-app preview UI and every tabular
// sheet ships with autofilters. This is the documented limitation.
// ================================================================
import ExcelJS from 'exceljs'
import { round2 } from './aggregation.js'
import { dateRangeLabel } from './filters.js'
import { REPORT_TIMEZONE, CURRENCY } from './filters.js'

const BRAND = {
  primary: '5C1A1A',
  gold: 'C9962C',
  goldLight: 'FEF9EB',
  alt: 'F9F8F6',
  white: 'FFFFFF',
  muted: '6B7280',
  green: '16A34A',
  red: 'DC2626',
  amber: 'B45309'
}

const FMT = {
  inr: '"₹"#,##0.00;[Red]-"₹"#,##0.00',
  inr0: '"₹"#,##0;[Red]-"₹"#,##0',
  num: '#,##0.00',
  num0: '#,##0',
  pct: '0.00%',
  date: 'dd-mmm-yyyy',
  datetime: 'dd-mmm-yyyy hh:mm',
  pctInt: '0.0"%"'
}

// ── Formula injection protection ────────────────────────────────────
// Any string starting with = + - @ is prefixed with a single quote so
// Excel treats it as literal text (prevents CSV/Excel formula injection
// via customer/product/address/SKU/imported text fields).
const DANGEROUS = /^[=+\-@]/i
export function safeText(v) {
  if (v === null || v === undefined) return ''
  if (typeof v === 'number') return v
  const s = String(v)
  if (DANGEROUS.test(s)) return `'${s}`
  return s
}

const num = (v) => Number(v) || 0
const dtStr = (iso) => {
  if (!iso) return ''
  const d = new Date(iso)
  if (isNaN(d.getTime())) return ''
  return d.toLocaleString('en-IN', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit', hour12: true })
}
const timeStr = (iso) => {
  if (!iso) return ''
  const d = new Date(iso)
  if (isNaN(d.getTime())) return ''
  return d.toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit', hour12: true })
}
const deliveryStatus = (st) => {
  if (st === 'delivered') return 'Delivered'
  if (st === 'out_for_delivery') return 'Out for Delivery'
  if (st === 'shipped') return 'Shipped'
  if (st === 'packed') return 'Packed'
  if (['cancelled', 'rejected', 'vendor_rejected', 'admin_rejected'].includes(st)) return 'Cancelled'
  if (st === 'returned') return 'Returned'
  return 'In Progress'
}

function headerStyle(cell) {
  cell.font = { bold: true, color: { argb: 'FFFFFFFF' }, size: 10, name: 'Calibri' }
  cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: `FF${BRAND.primary}` } }
  cell.alignment = { vertical: 'middle', horizontal: 'center', wrapText: true }
  cell.border = { bottom: { style: 'thin', color: { argb: 'FFC9962C' } } }
}
function bandedStyle(cell, rowIdx) {
  if (rowIdx % 2 === 0) {
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: `FF${BRAND.alt}` } }
  }
}
function titleBlock(ws, report, ncols) {
  const meta = report.meta
  const lastCol = columnLetter(ncols)
  ws.mergeCells(`A1:${lastCol}1`)
  ws.getCell('A1').value = 'AK ENTERPRISES'
  ws.getCell('A1').font = { bold: true, size: 16, color: { argb: `FF${BRAND.primary}` } }
  ws.getCell('A1').fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: `FF${BRAND.goldLight}` } }
  ws.getCell('A1').alignment = { vertical: 'middle', horizontal: 'left', indent: 1 }
  ws.getRow(1).height = 24

  ws.mergeCells(`A2:${lastCol}2`)
  ws.getCell('A2').value = meta.reportName
  ws.getCell('A2').font = { bold: true, size: 13 }
  ws.getCell('A2').alignment = { vertical: 'middle', horizontal: 'left', indent: 1 }
  ws.getRow(2).height = 20

  ws.mergeCells(`A3:${lastCol}3`)
  const lines = [
    `Generated At: ${dtStr(meta.generatedAt)}   |   Zone: ${meta.zoneName}   |   Period: ${meta.dateRangeLabel}   |   Currency: ${CURRENCY}`,
    `Generated By: ${meta.generatedBy || 'AK Enterprises'}   |   Timezone: ${REPORT_TIMEZONE}   |   Filters: ${filterLabel(meta.filters)}`
  ]
  ws.getCell('A3').value = lines[0]
  ws.getCell('A3').font = { size: 9, color: { argb: `FF${BRAND.muted}` } }
  ws.getCell('A3').alignment = { vertical: 'middle', horizontal: 'left', indent: 1 }
  ws.mergeCells(`A4:${lastCol}4`)
  ws.getCell('A4').value = lines[1]
  ws.getCell('A4').font = { size: 9, color: { argb: `FF${BRAND.muted}` } }
  ws.getCell('A4').alignment = { vertical: 'middle', horizontal: 'left', indent: 1 }
  ws.getRow(5).height = 6
}
function filterLabel(f) {
  if (!f) return 'None'
  const parts = []
  if (f.status && f.status !== 'all') parts.push(`Status: ${f.status}`)
  if (f.payment_status && f.payment_status !== 'all') parts.push(`Payment: ${f.payment_status}`)
  if (f.brand) parts.push(`Brand: ${f.brand}`)
  if (f.category_id) parts.push(`Category: ${f.category_id}`)
  if (f.state) parts.push(`State: ${f.state}`)
  if (f.city) parts.push(`City: ${f.city}`)
  if (f.zone_id) parts.push(`Zone: ${f.zone_id}`)
  if (parts.length === 0) parts.push('All orders')
  return parts.join(' · ')
}
function columnLetter(n) {
  let s = ''
  while (n > 0) {
    const rem = (n - 1) % 26
    s = String.fromCharCode(65 + rem) + s
    n = Math.floor((n - 1) / 26)
  }
  return s
}

// ── Generic tabular sheet writer ─────────────────────────────────────
// rows: array of objects keyed by column.key. columns may carry
// {header, key, width, numFmt, sum, align, wrap, cond}.
function writeDataSheet(wb, opts) {
  const { name, title, subtitle, columns, rows, totalsKeys, banded = true, landscape = true } = opts
  const ws = wb.addWorksheet(name, { pageSetup: { orientation: landscape ? 'landscape' : 'portrait', fitToWidth: 1, fitToHeight: 0, paperSize: 9, printArea: `A1:${columnLetter(columns.length)}${rows.length + 7}` } })
  ws.pageSetup.printTitlesRow = '1:6'
  ws.pageSetup.margins = { left: 0.3, right: 0.3, top: 0.5, bottom: 0.5, header: 0.2, footer: 0.2 }
  ws.properties.defaultRowHeight = 18

  // columns widths
  ws.columns = columns.map((c) => ({ width: c.width || 12, key: c.key }))

  // title block occupies rows 1..5, header at row 6, data from row 7
  titleBlock(ws, opts.report, columns.length)

  const hdrRow = 6
  ws.getRow(hdrRow).values = columns.map((c) => c.header)
  ws.getRow(hdrRow).eachCell((cell) => headerStyle(cell))
  ws.getRow(hdrRow).height = 26

  let r = hdrRow + 1
  for (let i = 0; i < rows.length; i++) {
    const row = rows[i]
    const rowObj = ws.getRow(r)
    columns.forEach((c, ci) => {
      let v = row[c.key]
      if (typeof v === 'function') v = v(row)
      if (typeof v === 'string' && !c.numFmt) v = safeText(v)
      const cell = rowObj.getCell(ci + 1)
      cell.value = v
      if (c.numFmt) cell.numFmt = c.numFmt
      if (banded) bandedStyle(cell, r)
      cell.alignment = { vertical: 'top', horizontal: c.align || 'left', wrapText: c.wrap !== false }
      if (c.cond) applyCondStyle(cell, c.cond, v)
    })
    r++
  }

  // totals row
  if (totalsKeys && totalsKeys.length) {
    const rowObj = ws.getRow(r)
    columns.forEach((c, ci) => {
      if (c.key === 'totals_label') {
        rowObj.getCell(ci + 1).value = 'TOTAL'
      } else if (totalsKeys.includes(c.key)) {
        const sum = rows.reduce((s, row) => s + num(row[c.key]), 0)
        rowObj.getCell(ci + 1).value = round2(sum)
        rowObj.getCell(ci + 1).numFmt = c.numFmt || FMT.inr
      } else {
        rowObj.getCell(ci + 1).value = ''
      }
      rowObj.getCell(ci + 1).font = { bold: true }
      rowObj.getCell(ci + 1).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: `FF${BRAND.goldLight}` } }
    })
    r++
  }

  // freeze panes + autofilter
  ws.views = [{ state: 'frozen', ySplit: hdrRow }]
  if (rows.length > 0) {
    ws.autoFilter = { from: { row: hdrRow, column: 1 }, to: { row: r - 1, column: columns.length } }
  }

  // conditional formatting (cell-based rules) — applied across data range
  const lastRow = Math.max(hdrRow + 1, r - 1)
  for (const c of columns) {
    if (c.cond && c.cond.rules) {
      const ci = columnLetter(columns.indexOf(c) + 1)
      ws.addConditionalFormatting({
        ref: `${ci}${hdrRow + 1}:${ci}${Math.min(lastRow, hdrRow + 1000)}`,
        rules: c.cond.rules.map((rule) => ({
          type: rule.type || 'cellIs',
          operator: rule.operator || 'equal',
          formulae: rule.formulae || [''],
          style: rule.style || {}
        }))
      })
    }
  }

  return ws
}

// Conditional style for cell-based colouring (statuses).
function applyCondStyle(cell, cond, value) {
  if (!cond || cond.map) return
  if (cond.rules) return // handled by Excel conditional formatting
}

// ── KPI label/value pair ─────────────────────────────────────────────
function kv(ws, row, label, value, fmt = FMT.num, bold = false, section = false) {
  const lc = ws.getCell(`A${row}`)
  const vc = ws.getCell(`B${row}`)
  if (section) {
    lc.value = label.toUpperCase()
    lc.font = { bold: true, color: { argb: `FF${BRAND.white}` } }
    lc.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: `FF${BRAND.gold}` } }
    vc.value = ''
    return
  }
  lc.value = label
  lc.font = { size: 10, color: { argb: `FF${BRAND.muted}` } }
  vc.value = value
  vc.numFmt = fmt
  vc.font = { bold: bold, size: 10 }
  lc.border = { bottom: { style: 'hair', color: { argb: 'FFE5E7EB' } } }
  vc.border = { bottom: { style: 'hair', color: { argb: 'FFE5E7EB' } } }
}

// ── Sheet builders ───────────────────────────────────────────────────

function buildSalesSummary(wb, report) {
  const s = report.summary
  const ws = wb.addWorksheet('Sales Summary', { pageSetup: { orientation: 'landscape', fitToWidth: 1, paperSize: 9 } })
  ws.columns = [{ width: 34 }, { width: 20 }, { width: 30 }, { width: 20 }]
  titleBlock(ws, report, 4)

  let r = 6
  kv(ws, r++, 'KEY METRICS', '', null, false, true)
  const kpi = [
    ['Total Orders', s.totalOrders, FMT.num0],
    ['Total Unique Customers', s.uniqueCustomers, FMT.num0],
    ['Total Products Sold', s.totalProductsSold, FMT.num0],
    ['Total Delivered Products', s.totalDeliveredProducts, FMT.num0],
    ['New Customers', s.newCustomers, FMT.num0],
    ['Repeat Customers', s.repeatCustomers, FMT.num0],
    ['Gross Sales', s.grossSales, FMT.inr],
    ['Taxable Amount', s.taxableAmount, FMT.inr],
    ['Total Discounts', s.totalDiscounts, FMT.inr],
    ['Total GST', s.totalGST, FMT.inr],
    ['Total Shipping Charges', s.totalShipping, FMT.inr],
    ['Total Refunds', s.totalRefunds, FMT.inr],
    ['Returns Value', s.totalReturnsValue, FMT.inr],
    ['Net Revenue', s.netRevenue, FMT.inr],
    ['Average Order Value (net)', s.avgOrderValue, FMT.inr],
    ['Avg Items Per Order', s.avgItemsPerOrder, FMT.num],
    ['Avg Customer Order Value', s.avgCustomerOrderValue, FMT.inr]
  ]
  for (const [label, val, fmt] of kpi) kv(ws, r++, label, val, fmt, true)

  kv(ws, r++, '', '', null, false, false)
  kv(ws, r++, 'ORDER STATUS', '', null, false, true)
  const statusRows = [
    ['Delivered Orders', s.deliveredOrders],
    ['Pending Orders', s.pendingOrders],
    ['Processing Orders', s.processingOrders],
    ['Shipped / Out for Delivery', s.shippedOrders],
    ['Cancelled / Rejected', s.cancelledOrders],
    ['Returned', s.returnedOrders]
  ]
  for (const [label, val] of statusRows) kv(ws, r++, label, val, FMT.num0)

  kv(ws, r++, '', '', null, false, false)
  kv(ws, r++, 'PAYMENT', '', null, false, true)
  const payRows = [
    ['Paid Orders', s.paidOrders],
    ['Unpaid / Pending Orders', s.unpaidOrders],
    ['Partially Paid Orders', s.partiallyPaidOrders]
  ]
  for (const [label, val] of payRows) kv(ws, r++, label, val, FMT.num0)

  kv(ws, r++, '', '', null, false, false)
  kv(ws, r++, 'RECONCILIATION', '', null, false, true)
  const rec = report.reconciliation || {}
  kv(ws, r++, 'Report Orders', rec.reportOrders ?? report.summary.totalOrders, FMT.num0)
  kv(ws, r++, 'Net Revenue (report)', rec.reportNetRevenue ?? report.summary.netRevenue, FMT.inr)
  kv(ws, r++, 'Orders-page revenue', rec.ordersPageRevenue ?? 0, FMT.inr)
  kv(ws, r++, 'Totals match', rec.revenueMatches === true ? 'YES' : 'MISMATCH', null, true)
  if (rec.revenueMatches !== true) {
    ws.getCell(`B${r - 1}`).font = { bold: true, color: { argb: `FF${BRAND.red}` } }
  }

  kv(ws, r++, '', '', null, false, false)
  kv(ws, r++, 'DATA QUALITY', '', null, false, true)
  const dq = report.dataQuality || {}
  kv(ws, r++, 'Lines missing GSTIN', dq.missingGstin ?? 0, FMT.num0)
  kv(ws, r++, 'Lines missing HSN code', dq.missingHsn ?? 0, FMT.num0)
  kv(ws, r++, 'Lines missing city', dq.missingCity ?? 0, FMT.num0)
  kv(ws, r++, 'Lines missing company', dq.missingCompany ?? 0, FMT.num0)
  kv(ws, r++, 'Lines missing zone', dq.missingZone ?? 0, FMT.num0)

  ws.views = [{ state: 'frozen', ySplit: 6 }]
  return ws
}

function buildDefinitions(wb, report) {
  const ws = wb.addWorksheet('Calculation Definitions', { pageSetup: { orientation: 'landscape', fitToWidth: 1 } })
  ws.columns = [{ width: 34 }, { width: 90 }]
  ws.mergeCells('A1:B1')
  ws.getCell('A1').value = 'REPORT CALCULATION DEFINITIONS'
  ws.getCell('A1').font = { bold: true, size: 13, color: { argb: `FF${BRAND.primary}` } }
  const rows = [
    ['Timezone', 'All dates are interpreted in Asia/Kolkata (IST). Half-open ranges: placed_at >= start AND placed_at < next day after end — orders on the end date are always included.'],
    ['Gross Sales', 'Sum of order-item line totals (price_snapshot x quantity) for orders NOT in {cancelled, rejected, vendor_rejected, admin_rejected, returned}. GST-inclusive.'],
    ['Taxable Amount', 'Gross Sales − Total GST (GST backed out of GST-inclusive prices).'],
    ['Total GST', 'Computed at report time per line via taxable = incl/(1+rate/100), tax = incl − taxable. Same-state (Maharashtra) → CGST=SGST=half; other state → IGST=full. Uses CURRENT products.gst_percent — NOT a stored snapshot.'],
    ['Discounts', 'Order-level discount (orders.discount) only — this is the real accounting discount. Columns marked * (Item Discount / MRP savings) are INFORMATIONAL: the selling price already reflects the discount, so MRP savings are never subtracted from revenue. Order-level discount is allocated across lines proportionally to line value.'],
    ['Shipping', 'Sum of orders.shipping_fee for included orders.'],
    ['Refunds / Returns', 'Currently 0 unless return_requests data is populated. Returns value = Gross Sales of orders with status "returned".'],
    ['Net Revenue', 'Gross Sales + Shipping − Discounts − Refunds − Returns value. Matches the Orders page which sums order.total for non-cancelled orders.'],
    ['Average Order Value', 'Net Revenue ÷ count of active (non-cancelled) orders. Labeled NET AOV.'],
    ['Average Items Per Order', 'Total Products Sold ÷ active order count.'],
    ['Average Customer Order Value', 'Net Revenue ÷ unique active customers.'],
    ['Total Products Sold', 'Sum of order-item quantities for active orders.'],
    ['Delivered Products', 'Sum of quantities on orders with status = delivered.'],
    ['Pending Order', 'status in {pending, pending_vendor_acceptance, pending_admin_approval, vendor_accepted_pending_admin_approval}.'],
    ['Delivered Order', 'status = delivered.'],
    ['Customer Type', 'New = first-ever order inside the period. Repeat = >1 order in period (or prior history). Dormant = has orders before the period but none in it.'],
    ['Currency', `Indian Rupee (INR / ₹). All money columns use ₹ #,##0.00 format; negatives shown in red.`],
    ['Excel Formula Protection', 'Cell text beginning with = + - @ is prefixed with a single quote so formulas are never executed from imported data.'],
    ['Excluded Statuses', 'cancelled, rejected, vendor_rejected, admin_rejected, returned — excluded from revenue/product/customer aggregates but listed in Order Details and the Order Status report.']
  ]
  let r = 3
  for (const [k, v] of rows) {
    ws.getCell(`A${r}`).value = k
    ws.getCell(`A${r}`).font = { bold: true, size: 10 }
    ws.getCell(`B${r}`).value = v
    ws.getCell(`B${r}`).alignment = { wrapText: true, vertical: 'top' }
    ws.getRow(r).height = 30
    r++
  }
  return ws
}

function buildOrderDetails(wb, report) {
  const orderLevel = {}
  for (const os of report.orderSummaries) {
    orderLevel[os.order_id] = { names: os.product_names, shipping: os.shipping_fee }
  }
  const columns = [
    { key: 'order_number', header: 'Order Number', width: 16 },
    { key: 'invoice_number', header: 'Invoice Number', width: 16 },
    { key: 'order_id', header: 'Order ID', width: 38 },
    { key: 'order_status', header: 'Order Status', width: 22, cond: { rules: statusRules() } },
    { key: 'payment_status', header: 'Payment Status', width: 15 },
    { key: 'payment_method', header: 'Payment Method', width: 14 },
    { key: 'currency', header: 'Currency', width: 8 },
    { key: 'order_date', header: 'Order Date', width: 12 },
    { key: 'order_time', header: 'Order Time', width: 10 },
    { key: 'last_updated', header: 'Last Updated', width: 18 },
    { key: 'customer_id', header: 'Customer ID', width: 38 },
    { key: 'customer_name', header: 'Customer Name', width: 24 },
    { key: 'first_name', header: 'Customer First Name', width: 18 },
    { key: 'last_name', header: 'Customer Last Name', width: 18 },
    { key: 'company_name', header: 'Company Name', width: 24 },
    { key: 'gstin', header: 'GSTIN', width: 18 },
    { key: 'email', header: 'Customer Email', width: 26 },
    { key: 'phone', header: 'Customer Contact', width: 16 },
    { key: 'alt_phone', header: 'Alternate Contact', width: 16 },
    { key: 'line1', header: 'Address Line 1', width: 28 },
    { key: 'line2', header: 'Address Line 2', width: 28 },
    { key: 'location', header: 'Customer Location', width: 18 },
    { key: 'city', header: 'City', width: 16 },
    { key: 'state', header: 'State', width: 18 },
    { key: 'country', header: 'Country', width: 10 },
    { key: 'pincode', header: 'Pin Code', width: 10 },
    { key: 'zone_name', header: 'Zone Name', width: 22 },
    { key: 'zone_id', header: 'Zone ID', width: 38 },
    { key: 'product_id', header: 'Product ID', width: 38 },
    { key: 'sku', header: 'SKU', width: 14 },
    { key: 'product_name', header: 'Product Name', width: 32 },
    { key: 'product_names_in_order', header: 'Product Names in Order', width: 40 },
    { key: 'hsn_code', header: 'HSN Code', width: 12 },
    { key: 'category', header: 'Product Category', width: 20 },
    { key: 'brand', header: 'Product Brand', width: 18 },
    { key: 'variant', header: 'Product Variant', width: 14 },
    { key: 'size', header: 'Product Size', width: 12 },
    { key: 'color', header: 'Product Color', width: 12 },
    { key: 'unit', header: 'Product Unit', width: 10 },
    { key: 'quantity', header: 'Quantity', width: 10, numFmt: FMT.num0, align: 'right', sum: true },
    { key: 'actual_price', header: 'Product Actual Price (MRP)', width: 16, numFmt: FMT.inr, align: 'right' },
    { key: 'selling_price', header: 'Product Selling Price', width: 16, numFmt: FMT.inr, align: 'right' },
    { key: 'price_before_discount', header: 'Price Before Discount', width: 16, numFmt: FMT.inr, align: 'right', sum: true },
    { key: 'item_discount', header: 'Item Discount (MRP savings)*', width: 16, numFmt: FMT.inr, align: 'right', sum: true },
    { key: 'order_discount_alloc', header: 'Order-Level Discount Alloc.', width: 16, numFmt: FMT.inr, align: 'right', sum: true },
    { key: 'total_discount', header: 'Total Discount*', width: 14, numFmt: FMT.inr, align: 'right', sum: true },
    { key: 'taxable_amount', header: 'Taxable Amount', width: 16, numFmt: FMT.inr, align: 'right', sum: true },
    { key: 'gst_percent', header: 'GST %', width: 10, numFmt: FMT.pctInt, align: 'right' },
    { key: 'cgst_percent', header: 'CGST %', width: 10, numFmt: FMT.pctInt, align: 'right' },
    { key: 'sgst_percent', header: 'SGST %', width: 10, numFmt: FMT.pctInt, align: 'right' },
    { key: 'igst_percent', header: 'IGST %', width: 10, numFmt: FMT.pctInt, align: 'right' },
    { key: 'cgst_amount', header: 'CGST Amount', width: 14, numFmt: FMT.inr, align: 'right', sum: true },
    { key: 'sgst_amount', header: 'SGST Amount', width: 14, numFmt: FMT.inr, align: 'right', sum: true },
    { key: 'igst_amount', header: 'IGST Amount', width: 14, numFmt: FMT.inr, align: 'right', sum: true },
    { key: 'total_gst', header: 'Total GST', width: 14, numFmt: FMT.inr, align: 'right', sum: true },
    { key: 'shipping_charge', header: 'Shipping Charge', width: 14, numFmt: FMT.inr, align: 'right' },
    { key: 'other_charges', header: 'Other Charges', width: 12, numFmt: FMT.inr, align: 'right' },
    { key: 'refund_amount', header: 'Refund Amount', width: 13, numFmt: FMT.inr, align: 'right' },
    { key: 'return_amount', header: 'Return Amount', width: 13, numFmt: FMT.inr, align: 'right' },
    { key: 'total_price', header: 'Total Price', width: 15, numFmt: FMT.inr, align: 'right', sum: true },
    { key: 'final_order_amount', header: 'Final Order Amount', width: 16, numFmt: FMT.inr, align: 'right' },
    { key: 'amount_paid', header: 'Amount Paid', width: 14, numFmt: FMT.inr, align: 'right', sum: true },
    { key: 'amount_due', header: 'Amount Due', width: 14, numFmt: FMT.inr, align: 'right', sum: true },
    { key: 'shipping_status', header: 'Shipping Status', width: 18 },
    { key: 'delivery_status', header: 'Delivery Status', width: 16 },
    { key: 'delivered_quantity', header: 'Delivered Qty', width: 12, numFmt: FMT.num0, align: 'right', sum: true },
    { key: 'returned_quantity', header: 'Returned Qty', width: 12, numFmt: FMT.num0, align: 'right', sum: true },
    { key: 'cancelled_quantity', header: 'Cancelled Qty', width: 13, numFmt: FMT.num0, align: 'right', sum: true },
    { key: 'coupon_code', header: 'Coupon Code', width: 14 },
    { key: 'coupon_discount', header: 'Coupon Discount', width: 14, numFmt: FMT.inr, align: 'right' },
    { key: 'referral_code', header: 'Referral Code', width: 14 },
    { key: 'sales_source', header: 'Sales Source', width: 14 },
    { key: 'created_by', header: 'Created By', width: 16 },
    { key: 'assigned_salesperson', header: 'Assigned Salesperson', width: 20 },
    { key: 'record_created_date', header: 'Record Created Date', width: 18 },
    { key: 'record_updated_date', header: 'Record Updated Date', width: 18 }
  ]

  const rows = report.orderDetails.map((l) => {
    const paid = String(l.payment_status).toLowerCase() === 'paid'
    const nameParts = String(l.customer_name || '').trim().split(/\s+/)
    const ol = orderLevel[l.order_id] || { names: '', shipping: 0 }
    return {
      order_number: l.order_number,
      invoice_number: l.invoice_number,
      order_id: l.order_id,
      order_status: l.order_status,
      payment_status: l.payment_status,
      payment_method: l.payment_method,
      currency: l.currency,
      order_date: l.placed_date,
      order_time: timeStr(l.placed_at),
      last_updated: dtStr(l.updated_at),
      customer_id: l.customer_id,
      customer_name: l.customer_name,
      first_name: nameParts[0] || '',
      last_name: nameParts.slice(1).join(' ') || '',
      company_name: l.customer_company,
      gstin: l.customer_gstin,
      email: l.customer_email,
      phone: l.customer_phone,
      alt_phone: '',
      line1: l.line1,
      line2: l.line2,
      location: l.city,
      city: l.city,
      state: l.state,
      country: l.country,
      pincode: l.pincode,
      zone_name: l.zone_name,
      zone_id: l.zone_id,
      product_id: l.product_id,
      sku: l.sku,
      product_name: l.product_name,
      product_names_in_order: ol.names,
      hsn_code: l.hsn_code,
      category: l.category,
      brand: l.brand,
      variant: l.variant_id,
      size: '',
      color: '',
      unit: l.unit,
      quantity: l.quantity,
      actual_price: l.mrp,
      selling_price: l.selling_price,
      price_before_discount: l.price_before_discount,
      item_discount: l.item_discount,
      order_discount_alloc: l.order_discount_alloc,
      total_discount: round2(l.item_discount + l.order_discount_alloc),
      taxable_amount: l.taxable_value,
      gst_percent: l.gst_percent,
      cgst_percent: l.cgst_percent,
      sgst_percent: l.sgst_percent,
      igst_percent: l.igst_percent,
      cgst_amount: l.cgst_amount,
      sgst_amount: l.sgst_amount,
      igst_amount: l.igst_amount,
      total_gst: l.gst_amount,
      shipping_charge: ol.shipping,
      other_charges: 0,
      refund_amount: 0,
      return_amount: 0,
      total_price: l.line_total,
      final_order_amount: l.final_order_amount,
      amount_paid: paid ? l.final_order_amount : 0,
      amount_due: paid ? 0 : l.final_order_amount,
      shipping_status: l.shipping_status,
      delivery_status: deliveryStatus(l.order_status),
      delivered_quantity: l.delivered_quantity,
      returned_quantity: l.returned_quantity,
      cancelled_quantity: l.cancelled_quantity,
      coupon_code: '',
      coupon_discount: 0,
      referral_code: '',
      sales_source: '',
      created_by: '',
      assigned_salesperson: '',
      record_created_date: dtStr(l.created_at),
      record_updated_date: dtStr(l.updated_at_order)
    }
  })

  const sumKeys = columns.filter((c) => c.sum).map((c) => c.key)
  return writeDataSheet(wb, { report, name: 'Order Details', columns, rows, totalsKeys: sumKeys })
}

function statusRules() {
  const color = (hex) => ({ font: { color: { argb: `FF${hex}`, bold: true } } })
  return [
    { type: 'cellIs', operator: 'equal', formulae: ['"delivered"'], style: color(BRAND.green) },
    { type: 'cellIs', operator: 'equal', formulae: ['"shipped"'], style: color('1D4ED8') },
    { type: 'cellIs', operator: 'equal', formulae: ['"out_for_delivery"'], style: color('4F46E5') },
    { type: 'cellIs', operator: 'equal', formulae: ['"packed"'], style: color('D97706') },
    { type: 'cellIs', operator: 'equal', formulae: ['"cancelled"'], style: color(BRAND.red) },
    { type: 'cellIs', operator: 'equal', formulae: ['"rejected"'], style: color(BRAND.red) },
    { type: 'cellIs', operator: 'equal', formulae: ['"vendor_rejected"'], style: color(BRAND.red) },
    { type: 'cellIs', operator: 'equal', formulae: ['"admin_rejected"'], style: color(BRAND.red) },
    { type: 'cellIs', operator: 'equal', formulae: ['"returned"'], style: color(BRAND.amber) }
  ]
}

function buildOrdersSummary(wb, report) {
  const columns = [
    { key: 'order_number', header: 'Order Number', width: 16 },
    { key: 'invoice_number', header: 'Invoice Number', width: 16 },
    { key: 'order_id', header: 'Order ID', width: 38 },
    { key: 'status', header: 'Order Status', width: 22, cond: { rules: statusRules() } },
    { key: 'payment_status', header: 'Payment Status', width: 15 },
    { key: 'payment_method', header: 'Payment Method', width: 14 },
    { key: 'placed_at', header: 'Order Date', width: 18 },
    { key: 'customer_id', header: 'Customer ID', width: 38 },
    { key: 'customer_name', header: 'Customer Name', width: 24 },
    { key: 'company_name', header: 'Company Name', width: 24 },
    { key: 'city', header: 'City', width: 16 },
    { key: 'state', header: 'State', width: 18 },
    { key: 'pincode', header: 'Pin Code', width: 10 },
    { key: 'zone_name', header: 'Zone Name', width: 22 },
    { key: 'product_names', header: 'Product Names in Order', width: 50 },
    { key: 'item_count', header: 'Items', width: 8, numFmt: FMT.num0, align: 'right' },
    { key: 'quantity', header: 'Quantity', width: 10, numFmt: FMT.num0, align: 'right', sum: true },
    { key: 'subtotal', header: 'Product Amount', width: 15, numFmt: FMT.inr, align: 'right', sum: true },
    { key: 'discount', header: 'Discount', width: 13, numFmt: FMT.inr, align: 'right', sum: true },
    { key: 'shipping_fee', header: 'Shipping', width: 12, numFmt: FMT.inr, align: 'right', sum: true },
    { key: 'gst', header: 'GST', width: 13, numFmt: FMT.inr, align: 'right', sum: true },
    { key: 'total', header: 'Total Order Amount', width: 16, numFmt: FMT.inr, align: 'right', sum: true },
    { key: 'active', header: 'Included in Revenue', width: 16 }
  ]
  const rows = report.orderSummaries.map((o) => ({
    order_number: o.order_number,
    invoice_number: o.invoice_number,
    order_id: o.order_id,
    status: o.status,
    payment_status: o.payment_status,
    payment_method: o.payment_method,
    placed_at: dtStr(o.placed_at),
    customer_id: o.customer_id,
    customer_name: o.customer_name,
    company_name: o.company_name,
    city: o.city,
    state: o.state,
    pincode: o.pincode,
    zone_name: o.zone_name,
    product_names: o.product_names,
    item_count: o.item_count,
    quantity: o.quantity,
    subtotal: o.subtotal,
    discount: o.discount,
    shipping_fee: o.shipping_fee,
    gst: o.gst,
    total: o.total,
    active: o.active ? 'Yes' : 'No'
  }))
  const sumKeys = columns.filter((c) => c.sum).map((c) => c.key)
  return writeDataSheet(wb, { report, name: 'Orders Summary', columns, rows, totalsKeys: sumKeys })
}

function buildProductsSold(wb, report) {
  const columns = [
    { key: 'product_id', header: 'Product ID', width: 38 },
    { key: 'sku', header: 'SKU', width: 14 },
    { key: 'name', header: 'Product Name', width: 34 },
    { key: 'category', header: 'Category', width: 20 },
    { key: 'hsn', header: 'HSN Code', width: 12 },
    { key: 'brand', header: 'Brand', width: 18 },
    { key: 'qtySold', header: 'Quantity Sold', width: 12, numFmt: FMT.num0, align: 'right', sum: true },
    { key: 'qtyDelivered', header: 'Delivered Qty', width: 12, numFmt: FMT.num0, align: 'right', sum: true },
    { key: 'qtyReturned', header: 'Returned Qty', width: 12, numFmt: FMT.num0, align: 'right', sum: true },
    { key: 'qtyCancelled', header: 'Cancelled Qty', width: 13, numFmt: FMT.num0, align: 'right', sum: true },
    { key: 'gross', header: 'Gross Sales', width: 15, numFmt: FMT.inr, align: 'right', sum: true },
    { key: 'discount', header: 'Discount', width: 13, numFmt: FMT.inr, align: 'right', sum: true },
    { key: 'gst', header: 'GST', width: 13, numFmt: FMT.inr, align: 'right', sum: true },
    { key: 'net', header: 'Net Revenue', width: 15, numFmt: FMT.inr, align: 'right', sum: true },
    { key: 'avgSellingPrice', header: 'Avg Selling Price', width: 14, numFmt: FMT.inr, align: 'right' },
    { key: 'qtyRank', header: 'Qty Rank', width: 9, numFmt: FMT.num0, align: 'right' },
    { key: 'revenueRank', header: 'Revenue Rank', width: 11, numFmt: FMT.num0, align: 'right' }
  ]
  const rows = report.byProduct.map((p) => p)
  const sumKeys = columns.filter((c) => c.sum).map((c) => c.key)
  return writeDataSheet(wb, { report, name: 'Products Sold', columns, rows, totalsKeys: sumKeys })
}

function buildSalesByDate(wb, report) {
  const columns = [
    { key: 'period', header: 'Period', width: 16 },
    { key: 'periodType', header: 'Period Type', width: 12 },
    { key: 'orders', header: 'Total Orders', width: 12, numFmt: FMT.num0, align: 'right', sum: true },
    { key: 'productsSold', header: 'Products Sold', width: 13, numFmt: FMT.num0, align: 'right', sum: true },
    { key: 'grossSales', header: 'Gross Sales', width: 15, numFmt: FMT.inr, align: 'right', sum: true },
    { key: 'discounts', header: 'Discounts', width: 13, numFmt: FMT.inr, align: 'right', sum: true },
    { key: 'gst', header: 'GST', width: 13, numFmt: FMT.inr, align: 'right', sum: true },
    { key: 'refunds', header: 'Refunds', width: 12, numFmt: FMT.inr, align: 'right', sum: true },
    { key: 'netRevenue', header: 'Net Revenue', width: 15, numFmt: FMT.inr, align: 'right', sum: true },
    { key: 'avgOrderValue', header: 'Avg Order Value', width: 14, numFmt: FMT.inr, align: 'right' }
  ]
  const rows = report.byDate.map((d) => ({ ...d, periodType: d.periodType || report.meta.filters.group_by || 'day' }))
  const sumKeys = columns.filter((c) => c.sum).map((c) => c.key)
  return writeDataSheet(wb, { report, name: 'Sales by Date', columns, rows, totalsKeys: sumKeys })
}

function buildSalesByProduct(wb, report) {
  // Analysis sheet: includes zero-sales products + rank + top/low highlights
  const columns = [
    { key: 'qtyRank', header: 'Qty Rank', width: 9, numFmt: FMT.num0, align: 'right' },
    { key: 'revenueRank', header: 'Revenue Rank', width: 12, numFmt: FMT.num0, align: 'right' },
    { key: 'product_id', header: 'Product ID', width: 38 },
    { key: 'sku', header: 'SKU', width: 14 },
    { key: 'name', header: 'Product Name', width: 34 },
    { key: 'category', header: 'Category', width: 20 },
    { key: 'hsn', header: 'HSN Code', width: 12 },
    { key: 'brand', header: 'Brand', width: 18 },
    { key: 'qtySold', header: 'Quantity Sold', width: 12, numFmt: FMT.num0, align: 'right' },
    { key: 'qtyDelivered', header: 'Delivered', width: 11, numFmt: FMT.num0, align: 'right' },
    { key: 'qtyReturned', header: 'Returned', width: 11, numFmt: FMT.num0, align: 'right' },
    { key: 'qtyCancelled', header: 'Cancelled', width: 11, numFmt: FMT.num0, align: 'right' },
    { key: 'gross', header: 'Gross Sales', width: 15, numFmt: FMT.inr, align: 'right' },
    { key: 'discount', header: 'Discount', width: 13, numFmt: FMT.inr, align: 'right' },
    { key: 'gst', header: 'GST', width: 13, numFmt: FMT.inr, align: 'right' },
    { key: 'net', header: 'Net Revenue', width: 15, numFmt: FMT.inr, align: 'right' },
    { key: 'avgSellingPrice', header: 'Avg Selling Price', width: 14, numFmt: FMT.inr, align: 'right' }
  ]
  const rows = report.byProduct.map((p) => p)
  const ws = writeDataSheet(wb, { report, name: 'Sales by Product', columns, rows, totalsKeys: [] })
  // Conditional highlight: top sellers green, no-sales grey, low sellers amber
  const lastRow = Math.min(6 + rows.length, 6 + 1000)
  const ci = 'I' // Quantity Sold col index 9
  ws.addConditionalFormatting({
    ref: `I7:I${lastRow}`,
    rules: [
      { type: 'cellIs', operator: 'equal', formulae: ['0'], style: { font: { color: { argb: `FF${BRAND.muted}` } } } }
    ]
  })
  return ws
}

function buildSalesByCategory(wb, report) {
  const columns = [
    { key: 'category', header: 'Category', width: 26 },
    { key: 'orders', header: 'Orders Containing', width: 16, numFmt: FMT.num0, align: 'right' },
    { key: 'qty', header: 'Quantity Sold', width: 13, numFmt: FMT.num0, align: 'right' },
    { key: 'gross', header: 'Gross Sales', width: 15, numFmt: FMT.inr, align: 'right' },
    { key: 'discounts', header: 'Discounts', width: 13, numFmt: FMT.inr, align: 'right' },
    { key: 'gst', header: 'GST', width: 13, numFmt: FMT.inr, align: 'right' },
    { key: 'net', header: 'Net Revenue', width: 15, numFmt: FMT.inr, align: 'right' },
    { key: 'pctOfRevenue', header: '% of Total Revenue', width: 16, numFmt: FMT.pct, align: 'right' }
  ]
  const rows = report.byCategory.map((c) => ({ ...c, pctOfRevenue: c.pctOfRevenue / 100 }))
  const sumKeys = ['orders', 'qty', 'gross', 'discounts', 'gst', 'net']
  return writeDataSheet(wb, { report, name: 'Sales by Category', columns, rows, totalsKeys: sumKeys })
}

function buildSalesByCustomer(wb, report) {
  const columns = [
    { key: 'rank', header: 'Rank', width: 8, numFmt: FMT.num0, align: 'right' },
    { key: 'customer_id', header: 'Customer ID', width: 38 },
    { key: 'name', header: 'Customer Name', width: 24 },
    { key: 'company', header: 'Company Name', width: 24 },
    { key: 'email', header: 'Email', width: 26 },
    { key: 'phone', header: 'Contact', width: 16 },
    { key: 'city', header: 'City', width: 16 },
    { key: 'state', header: 'State', width: 18 },
    { key: 'country', header: 'Country', width: 10 },
    { key: 'totalOrders', header: 'Total Orders', width: 12, numFmt: FMT.num0, align: 'right' },
    { key: 'qty', header: 'Quantity Purchased', width: 16, numFmt: FMT.num0, align: 'right' },
    { key: 'gross', header: 'Gross Sales', width: 15, numFmt: FMT.inr, align: 'right' },
    { key: 'discount', header: 'Discount', width: 13, numFmt: FMT.inr, align: 'right' },
    { key: 'gst', header: 'GST', width: 13, numFmt: FMT.inr, align: 'right' },
    { key: 'refunds', header: 'Refunds', width: 12, numFmt: FMT.inr, align: 'right' },
    { key: 'net', header: 'Net Revenue', width: 15, numFmt: FMT.inr, align: 'right' },
    { key: 'firstOrder', header: 'First Order Date', width: 16 },
    { key: 'lastOrder', header: 'Latest Order Date', width: 16 },
    { key: 'type', header: 'Customer Type', width: 16 }
  ]
  const rows = report.byCustomer.map((c) => ({ ...c, firstOrder: dtStr(c.firstOrder), lastOrder: dtStr(c.lastOrder) }))
  return writeDataSheet(wb, { report, name: 'Sales by Customer', columns, rows, totalsKeys: ['totalOrders', 'qty', 'gross', 'discount', 'gst', 'refunds', 'net'] })
}

function buildSalesByLocation(wb, report) {
  const columns = [
    { key: 'country', header: 'Country', width: 12 },
    { key: 'state', header: 'State', width: 18 },
    { key: 'city', header: 'City', width: 16 },
    { key: 'pincode', header: 'Pin Code', width: 12 },
    { key: 'zone', header: 'Zone', width: 22 },
    { key: 'orders', header: 'Total Orders', width: 12, numFmt: FMT.num0, align: 'right' },
    { key: 'qty', header: 'Quantity Sold', width: 13, numFmt: FMT.num0, align: 'right' },
    { key: 'gross', header: 'Gross Sales', width: 15, numFmt: FMT.inr, align: 'right' },
    { key: 'gst', header: 'GST', width: 13, numFmt: FMT.inr, align: 'right' },
    { key: 'net', header: 'Net Revenue', width: 15, numFmt: FMT.inr, align: 'right' }
  ]
  return writeDataSheet(wb, { report, name: 'Sales by Location', columns, rows: report.byLocation, totalsKeys: ['orders', 'qty', 'gross', 'gst', 'net'] })
}

function buildPaymentReport(wb, report) {
  const columns = [
    { key: 'method', header: 'Payment Method', width: 18 },
    { key: 'status', header: 'Payment Status', width: 16 },
    { key: 'orders', header: 'Number of Orders', width: 16, numFmt: FMT.num0, align: 'right' },
    { key: 'gross', header: 'Gross Amount', width: 15, numFmt: FMT.inr, align: 'right' },
    { key: 'paid', header: 'Amount Paid', width: 14, numFmt: FMT.inr, align: 'right' },
    { key: 'due', header: 'Amount Due', width: 14, numFmt: FMT.inr, align: 'right' },
    { key: 'refunded', header: 'Refunded Amount', width: 14, numFmt: FMT.inr, align: 'right' },
    { key: 'net', header: 'Net Amount', width: 14, numFmt: FMT.inr, align: 'right' }
  ]
  return writeDataSheet(wb, { report, name: 'Payment Report', columns, rows: report.paymentReport, totalsKeys: ['orders', 'gross', 'paid', 'due', 'refunded', 'net'] })
}

function buildOrderStatusReport(wb, report) {
  const columns = [
    { key: 'status', header: 'Order Status', width: 28, cond: { rules: statusRules() } },
    { key: 'orders', header: 'Number of Orders', width: 16, numFmt: FMT.num0, align: 'right' },
    { key: 'quantity', header: 'Product Quantity', width: 15, numFmt: FMT.num0, align: 'right' },
    { key: 'gross', header: 'Gross Amount', width: 15, numFmt: FMT.inr, align: 'right' },
    { key: 'net', header: 'Net Amount', width: 15, numFmt: FMT.inr, align: 'right' },
    { key: 'pctOfOrders', header: '% of Orders', width: 12, numFmt: FMT.pct, align: 'right' }
  ]
  const rows = report.orderStatusReport.map((s) => ({ ...s, pctOfOrders: s.pctOfOrders / 100 }))
  return writeDataSheet(wb, { report, name: 'Order Status Report', columns, rows, totalsKeys: ['orders', 'quantity', 'gross', 'net'] })
}

function buildGSTReport(wb, report) {
  const columns = [
    { key: 'order_number', header: 'Order Number', width: 16 },
    { key: 'invoice_number', header: 'Invoice Number', width: 16 },
    { key: 'customer_name', header: 'Customer Name', width: 22 },
    { key: 'company_name', header: 'Company Name', width: 22 },
    { key: 'gstin', header: 'GSTIN', width: 18 },
    { key: 'state', header: 'State', width: 16 },
    { key: 'hsn_code', header: 'HSN Code', width: 12 },
    { key: 'product_name', header: 'Product Name', width: 32 },
    { key: 'quantity', header: 'Quantity', width: 10, numFmt: FMT.num0, align: 'right' },
    { key: 'taxable_amount', header: 'Taxable Amount', width: 15, numFmt: FMT.inr, align: 'right' },
    { key: 'gst_percent', header: 'GST %', width: 10, numFmt: FMT.pctInt, align: 'right' },
    { key: 'cgst', header: 'CGST', width: 12, numFmt: FMT.inr, align: 'right' },
    { key: 'sgst', header: 'SGST', width: 12, numFmt: FMT.inr, align: 'right' },
    { key: 'igst', header: 'IGST', width: 12, numFmt: FMT.inr, align: 'right' },
    { key: 'total_gst', header: 'Total GST', width: 12, numFmt: FMT.inr, align: 'right' },
    { key: 'invoice_amount', header: 'Total Invoice Amount', width: 16, numFmt: FMT.inr, align: 'right' }
  ]
  return writeDataSheet(wb, { report, name: 'GST Report', columns, rows: report.gstReport, totalsKeys: ['quantity', 'taxable_amount', 'cgst', 'sgst', 'igst', 'total_gst', 'invoice_amount'] })
}

function buildDataQuality(wb, report) {
  const ws = wb.addWorksheet('Data Quality', { pageSetup: { orientation: 'portrait', fitToWidth: 1 } })
  ws.columns = [{ width: 36 }, { width: 18 }]
  ws.mergeCells('A1:B1')
  ws.getCell('A1').value = 'DATA QUALITY WARNING'
  ws.getCell('A1').font = { bold: true, size: 13, color: { argb: `FF${BRAND.red}` } }
  ws.getCell('A1').fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: `FF${BRAND.goldLight}` } }
  ws.getCell('A3').value = 'Missing / unavailable fields are shown as blank or "Not available".'
  ws.getCell('A3').font = { italic: true, size: 10 }
  ws.getCell('A4').value = 'Counts below refer to line-level rows in the Order Details sheet.'
  ws.getCell('A4').font = { italic: true, size: 10 }

  const dq = report.dataQuality || {}
  const rows = [
    ['Orders in report', dq.orders],
    ['Lines missing GSTIN', dq.missingGstin],
    ['Lines missing HSN code', dq.missingHsn],
    ['Lines missing city', dq.missingCity],
    ['Lines missing company name', dq.missingCompany],
    ['Lines missing customer name', dq.missingCustomerName],
    ['Lines missing pincode', dq.missingPincode],
    ['Lines missing zone (unassigned)', dq.missingZone]
  ]
  let r = 6
  for (const [label, val] of rows) {
    ws.getCell(`A${r}`).value = label
    ws.getCell(`A${r}`).font = { size: 10 }
    ws.getCell(`B${r}`).value = val
    ws.getCell(`B${r}`).numFmt = FMT.num0
    ws.getCell(`B${r}`).font = { bold: true }
    if (val > 0) ws.getCell(`B${r}`).font = { bold: true, color: { argb: `FF${BRAND.red}` } }
    r++
  }
  ws.getCell('A12').value = 'Missing GSTIN/HSN are expected for older orders and are NOT invented by this report.'
  ws.getCell('A12').font = { italic: true, size: 9 }
  return ws
}

function buildNotes(wb, report) {
  const ws = wb.addWorksheet('Notes', { pageSetup: { orientation: 'portrait', fitToWidth: 1 } })
  ws.columns = [{ width: 30 }, { width: 110 }]
  ws.mergeCells('A1:B1')
  ws.getCell('A1').value = 'REPORT NOTES'
  ws.getCell('A1').font = { bold: true, size: 13, color: { argb: `FF${BRAND.primary}` } }
  const rows = [
    ['Charts & dashboards', 'Charts (sales by date, revenue by month, orders by status, top/low products, category & zone charts) are rendered in the in-app report preview. ExcelJS has no native chart or slicer engine; every tabular sheet ships with autofilters so you can analyse in Excel.'],
    ['GST note', 'GST/HSN are recomputed at report time from the CURRENT product gst_percent and the order shipping state — they are not stored snapshots. If a product tax rate changed after purchase, historical GST may differ from the original invoice.'],
    ['Zone note', 'A zone is the assigned Zonal Admin (vendor). Zone Name = vendor name, Zone ID = vendor id. Orders with no assignment are shown as "Unassigned".'],
    ['Currency', `All money columns are INR (₹). Negative amounts render in red.`],
    ['Filters applied', report.meta.dateRangeLabel]
  ]
  let r = 3
  for (const [k, v] of rows) {
    ws.getCell(`A${r}`).value = k
    ws.getCell(`A${r}`).font = { bold: true, size: 10 }
    ws.getCell(`B${r}`).value = v
    ws.getCell(`B${r}`).alignment = { wrapText: true, vertical: 'top' }
    ws.getRow(r).height = 30
    r++
  }
  return ws
}

// ── Main entry ───────────────────────────────────────────────────────
/**
 * Builds the complete workbook from a report object (from query-service).
 * @returns {Promise<Buffer>}
 */
export async function buildWorkbook(report) {
  const wb = new ExcelJS.Workbook()
  wb.creator = report.meta.generatedBy || 'AK Enterprises'
  wb.lastModifiedBy = 'AK Enterprises Reports'
  wb.created = new Date()
  wb.modified = new Date()
  wb.company = 'AK Enterprises'
  wb.subject = 'Sales & Orders Report'
  wb.keywords = 'report, sales, orders, gst, excel'

  buildSalesSummary(wb, report)
  buildDefinitions(wb, report)
  buildOrderDetails(wb, report)
  buildOrdersSummary(wb, report)
  buildProductsSold(wb, report)
  buildSalesByDate(wb, report)
  buildSalesByProduct(wb, report)
  buildSalesByCategory(wb, report)
  buildSalesByCustomer(wb, report)
  buildSalesByLocation(wb, report)
  buildPaymentReport(wb, report)
  buildOrderStatusReport(wb, report)
  buildGSTReport(wb, report)
  buildDataQuality(wb, report)
  buildNotes(wb, report)

  return wb.xlsx.writeBuffer()
}

/** Safe export file name per spec: AK_Enterprises_Order_Report_YYYY-MM-DD_HH-mm.xlsx */
export function reportFileName(zoneName = '') {
  const d = new Date()
  const pad = (n) => String(n).padStart(2, '0')
  const stamp = `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}_${pad(d.getHours())}-${pad(d.getMinutes())}`
  const zone = zoneName ? `_${String(zoneName).replace(/[^a-zA-Z0-9_-]/g, '_')}` : ''
  return `AK_Enterprises_Order_Report${zone}_${stamp}.xlsx`
}
